title: Lorenzo Poggioni
logo: /assets/profile.jpg
description: >
  PhD Student in Applied Mathematics <br>
  <a href="https://www.linkedin.com/in/lorenzo-poggioni-a326763a2/">LinkedIn</a> | 
  <a href="mailto:lorenzo.poggioni@proton.me">Email</a>

theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
url: "https://lpoggioni.github.io"

# Plugins (all supported natively by GitHub Pages)
plugins:
  - jekyll-sitemap                       # auto-generates /sitemap.xml
  - jekyll-seo-tag                       # optional: adds <meta> SEO tags

  # Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - jp.md~
  - "*.swp"